// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*! 
 * @file HelloWorld.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _HELLOWORLD_H_
#define _HELLOWORLD_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(HelloWorld_SOURCE)
#define HelloWorld_DllAPI __declspec( dllexport )
#else
#define HelloWorld_DllAPI __declspec( dllimport )
#endif // HelloWorld_SOURCE
#else
#define HelloWorld_DllAPI
#endif
#else
#define HelloWorld_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}

/*!
 * @brief This class represents the structure HelloWorld defined by the user in the IDL file.
 * @ingroup HELLOWORLD
 */
class HelloWorld
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport HelloWorld();
    
    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~HelloWorld();
    
    /*!
     * @brief Copy constructor.
     * @param x Reference to the object HelloWorld that will be copied.
     */
    eProsima_user_DllExport HelloWorld(const HelloWorld &x);
    
    /*!
     * @brief Move constructor.
     * @param x Reference to the object HelloWorld that will be copied.
     */
    eProsima_user_DllExport HelloWorld(HelloWorld &&x);
    
    /*!
     * @brief Copy assignment.
     * @param x Reference to the object HelloWorld that will be copied.
     */
    eProsima_user_DllExport HelloWorld& operator=(const HelloWorld &x);
    
    /*!
     * @brief Move assignment.
     * @param x Reference to the object HelloWorld that will be copied.
     */
    eProsima_user_DllExport HelloWorld& operator=(HelloWorld &&x);
    
    /*!
     * @brief This function sets a value in member forward
     * @param _forward New value for member forward
     */
    inline eProsima_user_DllExport void forward(int32_t _forward)
    {
        m_forward = _forward;
    }

    /*!
     * @brief This function returns the value of member forward
     * @return Value of member forward
     */
    inline eProsima_user_DllExport int32_t forward() const
    {
        return m_forward;
    }

    /*!
     * @brief This function returns a reference to member forward
     * @return Reference to member forward
     */
    inline eProsima_user_DllExport int32_t& forward()
    {
        return m_forward;
    }
    /*!
     * @brief This function sets a value in member direction
     * @param _direction New value for member direction
     */
    inline eProsima_user_DllExport void direction(int32_t _direction)
    {
        m_direction = _direction;
    }

    /*!
     * @brief This function returns the value of member direction
     * @return Value of member direction
     */
    inline eProsima_user_DllExport int32_t direction() const
    {
        return m_direction;
    }

    /*!
     * @brief This function returns a reference to member direction
     * @return Reference to member direction
     */
    inline eProsima_user_DllExport int32_t& direction()
    {
        return m_direction;
    }
    /*!
     * @brief This function sets a value in member emergencyStop
     * @param _emergencyStop New value for member emergencyStop
     */
    inline eProsima_user_DllExport void emergencyStop(int32_t _emergencyStop)
    {
        m_emergencyStop = _emergencyStop;
    }

    /*!
     * @brief This function returns the value of member emergencyStop
     * @return Value of member emergencyStop
     */
    inline eProsima_user_DllExport int32_t emergencyStop() const
    {
        return m_emergencyStop;
    }

    /*!
     * @brief This function returns a reference to member emergencyStop
     * @return Reference to member emergencyStop
     */
    inline eProsima_user_DllExport int32_t& emergencyStop()
    {
        return m_emergencyStop;
    }
    
    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const HelloWorld& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;
    
private:
    int32_t m_forward;
    int32_t m_direction;
    int32_t m_emergencyStop;
};

#endif // _HELLOWORLD_H_